config/urls.py
from django.contrib import admin
from django.urls import path, include
from diary import views

urlpatterns = [
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('common/', include('common.urls')),
]

diary/urls.py
from django.urls import path

from . import views

app_name = 'diary'   # name space

urlpatterns = [
    path('', views.index, name='index'),    # 메인
    path('<int:board_id>/', views.detail, name='detail'),   # 글 자세히 보기
    path('answer/create/<int:board_id>/', views.answer_board, name='answer_board'), # 댓글 작성
    path('post/write/', views.post_write, name='post_write'),   # 글 쓰기
    path('analyze/', views.analyze_emotion, name='analyze_emotion'),
    path('img/', views.img_emotion, name='img_emotion'),
]

diary/models.py
from botocore import model
from djongo import models   # MongoDB
from django.contrib.auth.models import User # 인증모듈

class Write(models.Model):
    board_subject = models.CharField(max_length=200)  # 제목
    board_content = models.TextField()    # 내용
    board_date = models.DateTimeField(auto_now_add=True)    # 생성날짜
    mem_name = models.TextField(max_length=20) # 글쓴이
    board_emo = models.TextField(max_length=100) # 감정
    board_img = models.TextField(max_length=100) # 이미지 분석 결과
    board_tag = models.TextField(max_length=100) # 태그
    imgread = models.TextField(max_length=20, null=True) # 이미지 파일명
    chkinfo = models.TextField(max_length=10) # 이미지 공개 유무

    class Meta:
        abstract = False

# 답변모델, 보통 PK는 ID로 자동생성 함
class Answer(models.Model):
    board = models.ForeignKey(Write, on_delete=models.CASCADE)    # Write에서 가져온 외래키, 질문이 지워지면 답변도 지워지게! (on_delete=models.CASCADE)
    answer_content = models.TextField()    # 내용
    answer_date = models.DateTimeField()    # 생성날짜
    mem_name = models.TextField(max_length=20) # 글쓴이

diary/forms.py
from django import forms
from diary.models import Write


class WriteForm(forms.ModelForm):
    class Meta:
        model = Write
        fields = ['board_subject', 'board_content', 'board_emo', 'board_img', 'board_tag']
        

diary/views.py
#-*- coding:utf-8-*-

from django.shortcuts import render, get_object_or_404, redirect
# from django.http import HttpResponse  # 헬로 월드 없애서 이제 필요 없음!
from .models import Write
from django.utils import timezone   # 시간표시 모듈
from .forms import WriteForm
from django.core.paginator import Paginator # 페이지 기능 모듈
from django.http import JsonResponse
import boto3 # AWS 모듈
import json
import pandas as pd # pandas 모듈
from django.conf import settings # AWS 세팅값을 사용하기 위해 settings 불러오기
from django.contrib.auth.models import User # 인증모듈
from datetime import datetime

# def index(request):
#     return HttpResponse("안녕하세요 diary에 오신것을 환영합니다.")

def index(request):
    """
    diary 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # index 페이지 = 1페이지
    # 조회
    board_list = Write.objects.order_by('-board_date') # 최신 순으로 질문 출력
    # 페이징처리
    paginator = Paginator(board_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'board_list': page_obj}  # 위에 선언한 board_list를 board_list에다가 집어 넣음(context라는 배열에!) JSON 형식임z

    return render(request, 'diary/board_list.html', context)  # 저장한 context 배열을 템플릿 안에 출력~ context는 파라미터!

def detail(request, board_id):   # board_id 객체를 가져옴
    """
    diary 내용 출력
    """
    board = Write.objects.get(id=board_id)
    context = {
        'board': board,
        'bucket' : settings.AWS_STORAGE_BUCKET_NAME,
        'region' : settings.AWS_REGION
        }
    return render(request, 'diary/board_detail.html', context)    # diary/board_detail.html에 context 파라미터로 넘겨줘라!

def answer_board(request, board_id):
    """
    diary 댓글 등록
    """
    board = get_object_or_404(Write, pk=board_id)   # 페이지 없으면 404 띄우기
    board.answer_set.create(answer_content=request.POST.get('content'), answer_date=timezone.now(), mem_name=request.user.username) # 내용, 시간, 이름
    return redirect('diary:detail', board_id=board.id)  # 리다이렉트 지정

def post_write(request):
    """
    diary 작성
    """
    if request.method == 'POST':
        form = WriteForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)  # post에 담기
            post.board_date = timezone.now()    # 작성 시간
            post.mem_name = request.user.username   # 이름
            post.chkinfo = request.POST["chkinfo"] # 사진 공개 유무

            # 사진이 공개 설정이고 분석 결과가 있을 경우
            if post.chkinfo == "pictrue" and post.board_img != "None":
                post.imgread = settings.imgread # 전역변수에서 이미지 파일명을 가져오기, 사진이 비공개 설정이면 imgread = null
            
            post.save()
            return redirect('diary:index')
    else:
        form = WriteForm()
    context = {
        'form': form
        }
    return render(request, 'diary/board_write.html', {'form': form})


def analyze_emotion(request):
    """
    감정 분석 및 핵심 단어(태그) 추출
    """
    if request.method == 'POST':
        data = json.loads(request.body)   #board_write.html 에서 넘어온 일기 내용 저장
        comprehend = boto3.client(service_name='comprehend', region_name='ap-northeast-2')   #컴프리핸드 선언

        result_sentiment = json.dumps(comprehend.detect_sentiment(Text=data.get('content'), LanguageCode="ko"), sort_keys=True)  #감정 분석 실시
        
        result_keyword = json.dumps(comprehend.detect_key_phrases(Text=data.get('content'), LanguageCode="ko"), sort_keys=True, indent=4)
        sub = json.loads(result_keyword)
        KeyPhrases = sub["KeyPhrases"]
        # keyPhrases[0]["Score"] 와 같은 방법으로 참조
        keyword = []
        
        for i in KeyPhrases :
            if i["Score"] >= 0.75 :
                keyword.append(i)

        # print(type(KeyPhrases))
        context = {
            'result_sentiment': result_sentiment,
            'result_keyword' : keyword
        }
        return JsonResponse(context)   #json 형식으로 반환


def img_emotion(request):
    """
    이미지 업로드 및 이미지 감정 분석 (AWS S3 & Rekognition)
    """
    # POST 요청 시
    if request.method == 'POST':
        bucket = settings.AWS_STORAGE_BUCKET_NAME # S3 버킷 이름
        region = settings.AWS_REGION # AWS 지역
        
        s3_client=boto3.client('s3', region) # S3 클라이언트
        img_file = request.FILES.get('picture') # 파일 저장
        file_name = datetime.now() # 현재 시간 저장
        file_name_str = file_name.strftime("%Y-%m-%d-%H-%M-%S")
        # filename = request.FILES['picture'].name # 파일명 변수 저장
        
        s3_client.upload_fileobj(img_file, bucket, file_name_str, ExtraArgs={"ContentType": img_file.content_type,}) # S3 업로드
        settings.imgread = file_name_str # write 모델에 넣기 위해 전역변수에 이미지 파일명 넣기

        client=boto3.client('rekognition', region) # AWS 모듈, 사용할 서비스
        response = client.detect_faces(Image={'S3Object':{'Bucket':bucket,'Name':settings.imgread}},Attributes=['ALL']) # 이미지 분석 응답

        # 감정 값만 저장하는 반복문
        for faceDetail in response['FaceDetails']:
            emotions = faceDetail['Emotions']

        df = pd.DataFrame(emotions) # 감정 값 데이터 가공

        result = {} # 감정값을 저장할 사전
        for i in df.itertuples(): # 감정값을 사전에 저장할 반복문
            result[i.Type] = i.Confidence # 타입을 키로, 컨피던스를 벨류로

        # type = str(df.Type[0]) # 가장 커서 맨 위에 있는 감정
        # confidence = str(df.Confidence[0]) # 가장 커서 맨 위에 있는 감정 비율
        # result = type + ' ' + confidence # 감정과 비율 모두 출력 시 사용

        # 감정 벨류가 75 이상이면 imgword에 감정 저장
        imgword = []
        for key, value in result.items():
            if value >= 75:
                imgword.append(key)
        
        # imgword에 저장된 감정 한글로 바꿔서 imgword_translate에 저장
        imgword_translate = []
        for word in imgword:
            if word == "HAPPY":
                imgword_translate.append("행복한")
            elif word == "SAD":
                imgword_translate.append("슬픈")
            elif word == "ANGRY":
                imgword_translate.append("화난")
            elif word == "CONFUSED":
                imgword_translate.append("혼란스러운")
            elif word == "DISGUSTED":
                imgword_translate.append("역겨운")
            elif word == "SURPRISED":
                imgword_translate.append("놀란")
            elif word == "CALM":
                imgword_translate.append("차분한")
            elif word == "FEAR":
                imgword_translate.append("무서운")
        
        context = {
            'rekognition': result,
            'result_imgword': imgword_translate
        }

        return JsonResponse(context) # Json 형태로 응답

templates/diary/board_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ board.board_subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            {% comment %} 이미지 파일이 null이 아니면 보여주기 {% endcomment %}
            {% if board.imgread != null %}
            <img src="https://{{ bucket }}.s3.{{ region }}.amazonaws.com/{{ board.imgread }}" width="500">
            {% endif %}
            <div class="card-text" style="white-space: pre-line;">{{ board.board_content }}</div><br>
            
                <label>Positive</label><br>
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" id="emo_Positive"
                         aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Neutral</label><br>
                <div class="progress">
                    <div class="progress-bar bg-info" role="progressbar" id="emo_Neutral"
                        aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Mixed</label><br>
                <div class="progress">
                    <div class="progress-bar bg-warning" role="progressbar"  id="emo_Mixed"
                        aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Negative</label><br>
                <div class="progress">
                    <div class="progress-bar bg-danger" role="progressbar"  id="emo_Negative"
                        aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Happy</label><br>
                <div class="progress">
                    <div class="progress-bar bg-happy" role="progressbar" id="board_img_happy"
                          aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Sad</label><br>
                <div class="progress">
                        <div class="progress-bar bg-sad" role="progressbar" id="board_img_sad"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Angry</label><br>
                <div class="progress">
                        <div class="progress-bar bg-angry" role="progressbar" id="board_img_angry"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Confused</label><br>
                <div class="progress">
                        <div class="progress-bar bg-confused" role="progressbar" id="board_img_confused"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Disgusted</label><br>
                <div class="progress">
                        <div class="progress-bar bg-disgusted" role="progressbar" id="board_img_disgusted"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Surprised</label><br>
                <div class="progress">
                        <div class="progress-bar bg-surprised" role="progressbar" id="board_img_surprised"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Calm</label><br>
                <div class="progress">
                        <div class="progress-bar bg-calm" role="progressbar" id="board_img_calm"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>Fear</label><br>
                <div class="progress">
                        <div class="progress-bar bg-fear" role="progressbar" id="board_img_fear"
                            aria-valuemin="0" aria-valuemax="100"></div>
                </div><br>
                <label>태그</label><br>
                <div class="form-group">
                    <input type="text" class="form-control" name="board_tag" id="board_tag" readonly
                           value="{{ board.board_tag }}">
                </div><br>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ board.mem_name }}
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ board.board_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{board.answer_set.count}}개의 댓글이 있습니다.</h5>
    {% for answer in board.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.answer_content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.mem_name }}
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.answer_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'diary:answer_board' board.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>

<script>
    var temporarily_data = "{{ board.board_emo }}"      // board_emo 저장
    var emotions = temporarily_data.split('/')          // split으로 가공
    var temporarily_image = "{{ board.board_img }}"
    var images = temporarily_image.split('/')

    // 각 프로그레스바 설정
    document.getElementById('emo_Positive').style.width = emotions[0] +'%';
    document.getElementById('emo_Neutral').style.width = emotions[1] +'%';
    document.getElementById('emo_Mixed').style.width = emotions[2] +'%';
    document.getElementById('emo_Negative').style.width = emotions[3] +'%';
    document.getElementById("board_img_happy").style.width = images[0] + '%';
    document.getElementById("board_img_sad").style.width = images[1] + '%';
    document.getElementById("board_img_angry").style.width = images[2] + '%';
    document.getElementById("board_img_confused").style.width = images[3] + '%';
    document.getElementById("board_img_disgusted").style.width = images[4] + '%';
    document.getElementById("board_img_surprised").style.width = images[5] + '%';
    document.getElementById("board_img_calm").style.width = images[6] + '%';
    document.getElementById("board_img_fear").style.width = images[7] + '%';
</script>



{% endblock %}

templates/diary/board_list.html
{% extends 'base.html' %}

{% load diary_filter %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="text-center thead-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if board_list %}
                {% for board in board_list %}
                    <tr class="text-center">
                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                            {{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td class="text-left">
                            <!-- 제목 -->
                            <a href="{% url 'diary:detail' board.id %}">{{ board.board_subject }}</a>
                            <!-- 댓글 갯수 -->
                            {% if board.answer_set.count > 0 %}
                            <span class="text-danger small ml-2">{{ board.answer_set.count }}</span>
                            {% endif %}
                        </td>
                        <td>{{ board.mem_name }}</td>  <!-- 글쓴이 추가 -->
                        <td>{{ board.board_date }}</td> <!-- 작성 날짜 추가 -->
                    </tr>
                {% endfor %}    
            {% else %}
                <tr>
                    <td colspan="3">게시글이 없어요!</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ board_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ board_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <a href="{% url 'diary:post_write' %}" class="btn btn-primary">게시글 쓰기</a>
</div>
{% endblock %}